-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer
(
    customer_id integer NOT NULL,
    cust_name text COLLATE pg_catalog."default" NOT NULL,
    city text COLLATE pg_catalog."default" NOT NULL,
    grade integer NOT NULL,
    salesman_id integer NOT NULL,
    CONSTRAINT "Customer_pkey" PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.salesman
(
    salesman_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    city text COLLATE pg_catalog."default" NOT NULL,
    commission numeric NOT NULL,
    CONSTRAINT "Salesman_pkey" PRIMARY KEY (salesman_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    ord_no integer NOT NULL,
    purch_amt numeric NOT NULL,
    ord_date date NOT NULL,
    customer_id integer NOT NULL,
    salesman_id integer NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (ord_no)
);

ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT fk FOREIGN KEY (salesman_id)
    REFERENCES public.salesman (salesman_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk FOREIGN KEY (salesman_id)
    REFERENCES public.salesman (salesman_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT salesman_id FOREIGN KEY (salesman_id)
    REFERENCES public.salesman (salesman_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;